Repository Dusk-Labs/dim, pull requests merged in 2021-06, with the labels that each got.

#117 Migrate from rocket to warp.
  .gitignore
  Cargo.toml
  src/auth/Cargo.toml
  src/auth/src/lib.rs
  src/core.rs
  src/database/Cargo.toml
  src/database/src/episode.rs
  src/database/src/lib.rs
  src/errors.rs
  src/lib.rs
  src/logger.rs
  src/main.rs
  src/routes/auth.rs
  src/routes/dashboard.rs
  src/routes/general.rs
  src/routes/library.rs
  src/routes/media.rs
  src/routes/mediafile.rs
  src/routes/mod.rs
  src/routes/statik.rs
  src/routes/stream.rs
  src/routes/tv.rs
  src/stream_tracking.rs
  src/tests/mod.rs
  src/tests/route_library_tests.rs
  src/tests/route_media_tests.rs
  src/tests/route_tv_tests.rs
  ui/src/Modals/NewLibrary/DirSelection.jsx
  yarn.lock
Labels: backend

#112 Add matching unmatched media
  ui/src/Components/CardList/Index.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/Context.js
  ui/src/Components/CardList/SelectUnmatchedMedia/FileControls.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/FileControls.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/Files.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/Files.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/Folders.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/Folders.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/Index.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/Index.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/MediaTypeSelection.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/MediaTypeSelection.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/Options.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/Options.scss
  ui/src/Components/CardList/SelectUnmatchedMedia/Search.jsx
  ui/src/Components/CardList/SelectUnmatchedMedia/Search.scss
  ui/src/Components/CardList/UnmatchedCardList.jsx
  ui/src/Components/CardList/UnmatchedCardList.scss
  ui/src/Modals/Image.jsx
  ui/src/Modals/Index.jsx
  ui/src/Modals/NewLibrary/DirSelection.jsx
  ui/src/Pages/Library/Index.jsx
  ui/src/assets/Icons/Check.jsx
Labels: new feature, ui

#143 Fix video seeking discrepancies on chrome
  ui/src/Pages/VideoPlayer/Events.jsx
  ui/src/Pages/VideoPlayer/Index.jsx
  ui/src/reducers/video/index.js
Labels: bug fix, ui

#145 Add recently viewed section
  migrations/sqlite/2019-03-07-120346_openflix/up.sql
  src/build.rs
  src/core.rs
  src/database/src/progress.rs
  src/database/src/tv.rs
  src/main.rs
  src/routes/dashboard.rs
  src/routes/statik.rs
  src/routes/stream.rs
Labels: backend

#147 Issue EventNewCard for tv shows.
  src/scanners/tv_show.rs
Labels: backend, scanners

#150 Fix postgres migrations
  .gitignore
  docker-compose.yml
  migrations/postgres/2019-03-07-120346_openflix/down.sql
  migrations/postgres/2019-03-07-120346_openflix/up.sql
  migrations/postgres/2019-08-25-232941_genres_table/down.sql
  migrations/postgres/2019-08-25-232941_genres_table/up.sql
  migrations/postgres/2019-11-10-232356_users/down.sql
  migrations/postgres/2019-11-10-232356_users/up.sql
  migrations/postgres/2019-12-13-210906_user_tracking/down.sql
  migrations/postgres/2019-12-13-210906_user_tracking/up.sql
  migrations/postgres/2020-01-22-182243_user_and_global_settings/down.sql
  migrations/postgres/2020-01-22-182243_user_and_global_settings/up.sql
  migrations/sqlite/2019-03-07-120346_openflix/down.sql
  migrations/sqlite/2019-03-07-120346_openflix/up.sql
  migrations/sqlite/2019-12-13-210906_user_tracking/down.sql
  migrations/sqlite/2019-12-13-210906_user_tracking/up.sql
  migrations/sqlite/2020-01-22-182243_user_and_global_settings/down.sql
  migrations/sqlite/2020-01-22-182243_user_and_global_settings/up.sql
  src/database/src/episode.rs
  src/database/src/genre.rs
  src/database/src/lib.rs
  src/database/src/main.rs
  src/database/src/media.rs
  src/database/src/mediafile.rs
  src/database/src/progress.rs
  src/database/src/season.rs
  src/database/src/tv.rs
  src/database/src/utils.rs
  src/lib.rs
  src/utils.rs
Labels: backend, db-postgres
