Repository Dusk-Labs/dim, pull requests merged in 2021-05, with the labels that each got.

#102 Add video volume slider
  ui/src/App.scss
  ui/src/Pages/VideoPlayer/Controls/Actions.jsx
  ui/src/Pages/VideoPlayer/Controls/Actions.scss
Labels: new feature, ui

#103 Fix BroadcastChannel error on safari
  ui/src/Routes/NotAuthedOnly.jsx
  ui/src/Routes/Private.jsx
  ui/src/actions/auth.js
Labels: bug fix, ui

#100 Implement virtual manifests
  Cargo.toml
  src/core.rs
  src/errors.rs
  src/lib.rs
  src/routes/media.rs
  src/routes/mod.rs
  src/routes/stream.rs
  src/static/audio_segment.mpd
  src/static/subtitle_segment.mpd
  src/static/video_segment.mpd
  src/stream_tracking.rs
  src/streaming/ffprobe.rs
  ui/.eslintrc
  ui/src/Components/CardList/Actions/Delete.jsx
  ui/src/Components/CardList/Ghost.jsx
  ui/src/Helpers/utils.js
  ui/src/Pages/Auth/Field.jsx
  ui/src/Pages/Media/Seasons.jsx
  ui/src/Pages/VideoPlayer/Controls/Actions.jsx
  ui/src/Pages/VideoPlayer/Controls/Actions.scss
  ui/src/Pages/VideoPlayer/Controls/Index.jsx
  ui/src/Pages/VideoPlayer/Controls/SeekBar.jsx
  ui/src/Pages/VideoPlayer/Controls/SeekingTo.jsx
  ui/src/Pages/VideoPlayer/Events.jsx
  ui/src/Pages/VideoPlayer/Index.jsx
  ui/src/Pages/VideoPlayer/Index.scss
  ui/src/Pages/VideoPlayer/Menus.jsx
  ui/src/Pages/VideoPlayer/Subtitles.jsx
  ui/src/Pages/VideoPlayer/Subtitles.scss
  ui/src/Routes/Private.jsx
  ui/src/actions/auth.js
  ui/src/actions/banner.js
  ui/src/actions/card.js
  ui/src/actions/fileBrowser.js
  ui/src/actions/library.js
  ui/src/actions/search.js
  ui/src/actions/user.js
  ui/src/reducers/auth.js
  ui/src/reducers/library.js
Labels: backend, improvements, new feature, ui

#111 refactor(ws): make the websocket logic more generic/hookable
  src/websocket.rs
Labels: backend
