Repository Dusk-Labs/dim, pull requests merged in 2021-04, with the labels that each got.

#65 Video player progress
  ui/package.json
  ui/src/App.jsx
  ui/src/Components/Banners/Banner.jsx
  ui/src/Components/CardList/Card.jsx
  ui/src/Components/CardList/Card.scss
  ui/src/Components/CardList/CardPopup.jsx
  ui/src/Components/CardList/Image.jsx
  ui/src/Components/PlayButton.jsx
  ui/src/Components/Sidebar/LogoutBtn.jsx
  ui/src/Helpers/utils.js
  ui/src/Modals/ConfirmationBox.jsx
  ui/src/Modals/Index.jsx
  ui/src/Modals/SelectMediaVersion.jsx
  ui/src/Pages/Library/Actions/Delete.jsx
  ui/src/Pages/Media/Seasons.jsx
  ui/src/Pages/VideoPlayer/ContinueProgress.jsx
  ui/src/Pages/VideoPlayer/Controls/Actions.jsx
  ui/src/Pages/VideoPlayer/Controls/Actions.scss
  ui/src/Pages/VideoPlayer/Controls/Index.jsx
  ui/src/Pages/VideoPlayer/Controls/Index.scss
  ui/src/Pages/VideoPlayer/Controls/SeekBar.jsx
  ui/src/Pages/VideoPlayer/ErrorBox.jsx
  ui/src/Pages/VideoPlayer/Index.jsx
  ui/src/Pages/VideoPlayer/Index.scss
  ui/src/Pages/VideoPlayer/Subtitles.jsx
  ui/src/Pages/VideoPlayer/Subtitles.scss
  ui/src/assets/Icons/CC.jsx
  ui/src/assets/Icons/Circle.jsx
Labels: bug, enhancement, ui

#81 Refactor redux
  src/routes/library.rs
  src/routes/media.rs
  src/scanners/mod.rs
  ui/src/App.jsx
  ui/src/Components/Banners/Banner.jsx
  ui/src/Components/Banners/Index.jsx
  ui/src/Components/CardList/Actions/Delete.jsx
  ui/src/Components/CardList/Card.jsx
  ui/src/Components/CardList/Card.scss
  ui/src/Components/CardList/CardPopup.jsx
  ui/src/Components/CardList/Dropdown.jsx
  ui/src/Components/CardList/Dropdown.scss
  ui/src/Components/CardList/Index.jsx
  ui/src/Components/CardList/Index.scss
  ui/src/Components/CardList/UnmatchedCardList.jsx
  ui/src/Components/Sidebar/Index.jsx
  ui/src/Components/Sidebar/Libraries.jsx
  ui/src/Components/Sidebar/LogoutBtn.jsx
  ui/src/Components/Sidebar/Profile/Index.jsx
  ui/src/Components/Sidebar/QuickSearchResults.jsx
  ui/src/Components/Sidebar/Search.jsx
  ui/src/Modals/NewLibrary/DirSelection.jsx
  ui/src/Modals/NewLibrary/Index.jsx
  ui/src/Pages/Auth/Login.jsx
  ui/src/Pages/Auth/LoginBtn.jsx
  ui/src/Pages/Auth/Register.jsx
  ui/src/Pages/Auth/RegisterBtn.jsx
  ui/src/Pages/Library/Actions.jsx
  ui/src/Pages/Library/Actions.scss
  ui/src/Pages/Library/Index.jsx
  ui/src/Pages/Media/Banner.jsx
  ui/src/Pages/Media/Index.jsx
  ui/src/Pages/Media/MetaContent.jsx
  ui/src/Pages/Media/Seasons.jsx
  ui/src/Pages/Preferences.jsx
  ui/src/Pages/SearchResults.jsx
  ui/src/Pages/VideoPlayer/ContinueProgress.jsx
  ui/src/Pages/VideoPlayer/Controls/SeekBar.jsx
  ui/src/Pages/VideoPlayer/Index.jsx
  ui/src/Routes/NotAuthedOnly.jsx
  ui/src/Routes/Private.jsx
  ui/src/actions/auth.js
  ui/src/actions/banner.js
  ui/src/actions/card.js
  ui/src/actions/fileBrowser.js
  ui/src/actions/library.js
  ui/src/actions/search.js
  ui/src/actions/types.js
  ui/src/actions/user.js
  ui/src/reducers/auth.js
  ui/src/reducers/banner.js
  ui/src/reducers/card.js
  ui/src/reducers/fileBrowser.js
  ui/src/reducers/library.js
  ui/src/reducers/root.js
  ui/src/reducers/search.js
  ui/src/reducers/user.js
Labels: improvements, ui

#84 Refactor scanners into actors, rewrite database to use tokio
  Cargo.toml
  benches/scanner.rs
  src/auth/Cargo.toml
  src/auth/src/lib.rs
  src/build.rs
  src/core.rs
  src/database/Cargo.toml
  src/database/src/episode.rs
  src/database/src/error.rs
  src/database/src/genre.rs
  src/database/src/lib.rs
  src/database/src/library.rs
  src/database/src/media.rs
  src/database/src/mediafile.rs
  src/database/src/movie.rs
  src/database/src/progress.rs
  src/database/src/season.rs
  src/database/src/streamable_media.rs
  src/database/src/tv.rs
  src/database/src/user.rs
  src/errors.rs
  src/lib.rs
  src/logger.rs
  src/main.rs
  src/routes/auth.rs
  src/routes/catchers.rs
  src/routes/dashboard.rs
  src/routes/external.rs
  src/routes/general.rs
  src/routes/library.rs
  src/routes/media.rs
  src/routes/mediafile.rs
  src/routes/mod.rs
  src/routes/statik.rs
  src/routes/stream.rs
  src/routes/tv.rs
  src/scanners/base.rs
  src/scanners/mod.rs
  src/scanners/movie.rs
  src/scanners/scanner_daemon.rs
  src/scanners/tmdb.rs
  src/scanners/tv_show.rs
  src/stream_tracking.rs
  src/streaming/ffprobe.rs
  src/tests/mod.rs
  src/websocket.rs
  ui/public/logo-dark-128.png
Labels: backend, improvements, new feature, scanners

#93 Stop caching paths in file browser
  ui/src/Modals/NewLibrary/DirSelection.jsx
  ui/src/reducers/fileBrowser.js
Labels: bug, ui

#97 Show season and episode in play button
  ui/src/Components/Banners/Banner.jsx
  ui/src/Components/CardList/CardPopup.jsx
  ui/src/Components/PlayButton.jsx
  ui/src/Pages/Media/MetaContent.jsx
Labels: improvements, ui

#94 Add proxy to backend server
  ui/package.json
  ui/src/App.jsx
  ui/src/Components/Banners/Image.jsx
  ui/src/Components/Banners/Index.jsx
  ui/src/Components/CardList/CardPopup.jsx
  ui/src/Components/CardList/Image.jsx
  ui/src/Components/CardList/Index.jsx
  ui/src/Components/Sidebar/Libraries.jsx
  ui/src/Pages/Dashboard.jsx
  ui/src/Pages/Library/Index.jsx
  ui/src/Pages/Media/BannerImage.jsx
  ui/src/Pages/Media/CardImage.jsx
  ui/src/Pages/Media/MetaContent.jsx
  ui/src/Pages/VideoPlayer/Controls/SeekBar.jsx
  ui/src/Pages/VideoPlayer/Index.jsx
  ui/src/Routes/Private.jsx
  ui/src/actions/auth.js
  ui/src/actions/banner.js
  ui/src/actions/card.js
  ui/src/actions/fileBrowser.js
  ui/src/actions/library.js
  ui/src/actions/search.js
  ui/src/actions/user.js
Labels: improvements, ui

#99 Round corners for screenshots
  README.md
Labels: documentation
